// angular-todo/src/app/to-do/to-do.component.ts
import { Component } from "@angular/core";
import { ToDo } from "./to-do";

@Component({
	selector: "ToDo", // default:'app-to-do',
	templateUrl: "./to-do.component.html",
	styleUrls: ["./to-do.component.css"]
})
export class ToDoComponent {
	constructor() { }

	toDos: ToDo[] = [
		new ToDo("clean the house"),
		new ToDo("buy milk")
	];

	input: string = "";

	hasBeenEdited: boolean = false;


	deleteItem(i: number) {
		this.toDos.splice(i, 1);
	}

	addItem() {
		if (this.input == "") {
			return alert("Please enter a todo!");
		}
		this.toDos.push(new ToDo(this.input));
		this.input = '';
		this.hasBeenEdited = false;
	}

	onKeyUp() {
		this.hasBeenEdited = true;
	}
}

<div class="ToDo">
	<img class="Logo" alt="Angular Logo" src="assets/Logo.svg" alt="image">
	<h1 class="ToDo-Header">Angular To Do</h1>
	<div class="ToDo-Container">
		<div class="ToDo-Content">
			<div *ngFor="let toDo of toDos; index as i">
				<ToDoItem [toDo]="toDo" (deleted)="deleteItem(i)"></ToDoItem>
			</div>
		</div>

		<form (ngSubmit)="addItem()" #todoForm="ngForm">
			<div class="form-group">
				<input type="text" class="form-control" id="name" [(ngModel)]="input" (keyup)="onKeyUp()" name="name" #name="ngModel" required>
				<div *ngIf="hasBeenEdited && !input">Name is required</div>
			</div>
			<button type="submit" class="ToDo-Add">+</button>
		</form>
	</div>
</div>

// vue-todo/src/ToDo.vue
<template>
  <div class="ToDo">
    <img class="Logo" src="./assets/logo.png" alt="Vue logo" />
    <h1 class="ToDo-Header">Vue To Do</h1>
    <div class="ToDo-Container">
      <div class="ToDo-Content">
        <ToDoItem v-for="todo in list" :todo="todo" :onDeleteItem="onDeleteItem" :key="todo.id" />
      </div>
      <input
        type="text"
        v-model="todo"
        @keyup="hasBeenEdited = true"
        @keyup.enter="createNewToDoItem"
      />
      <div v-if="!this.todo && hasBeenEdited">Name is required.</div>
      <div class="ToDo-Add" @click="createNewToDoItem()">+</div>
    </div>
  </div>
</template>

<script>
import { Vue, Component } from "vue-property-decorator";
import ToDoItem from "./components/ToDoItem.vue";

@Component({ components: { ToDoItem } })
export default class ToDo extends Vue {
  list = [
    {
      id: 1,
      text: "clean the house"
    },
    {
      id: 2,
      text: "buy milk"
    }
  ];
  todo = "";
  hasBeenEdited = false;
  idCounter = 2;

  createNewToDoItem() {
    if (!this.todo) {
      return alert("Please enter a todo!");
    }

    this.hasBeenEdited = false;
    this.idCounter++;
    this.list.push({ id: this.idCounter, text: this.todo });
    this.todo = "";
  }

  onDeleteItem(todo) {
    this.list = this.list.filter(item => item !== todo);
  }
}
</script>

<style src="./ToDo.css"></style>
